name: push docker image to gcr

on:
  push:
    tags:
      - '*'

jobs:
  push-docker-image-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: get the version
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build then push to gcr
        uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{ secrets.GC_GCR_SERVICE_KEY }}
          registry: us.gcr.io
          project_id: bilgge
          image_name: bilgge-ui
          image_tag: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}},latest
